# Secret de demostracion
# No contiene credenciales reales

apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
  namespace: proyecto-adsa
type: Opaque
stringData:
  PASSWORD: "clave-demo-adsa"

